### PR TITLE
Reading ecore eAnnotation

### PR DESCRIPTION
**Pull request by qvitech**
Hey Developers, 

I am working on a project where I am using emf4cpp. Library works great, however, there were some special cases which was not handled, so in this branch, you can really review the changes and merge in for those, who are further using the library.
PS: My ecore files are very complex and according to standards :)

### CODE REVIEW

**Comment by mcraveiro** [comment]
Hi @qvitech,

I'm also having a look at this project. Bit of an unrelated question, but just in case you can help me: do you have by any chance the original PDF of the project?

Andrés Senac González, Diego Sevilla Ruiz, Gregorio Martinez Perez, "EMF4CPP: a C++ Ecore Implementation", DSDM 2010 - Desarrollo de Software Dirigido por Modelos, Jornadas de Ingenieria del Software y Bases de Datos (JISBD 2010), Valencia, Spain, September 2010.


The link on the front page is broken and I cannot find anything at all in Google.

Thanks

**Comment by qvitech** [comment]
Hi @mcraveiro ,

Nope sorry, we only used the documentation available in project description. The library follows the general concepts from Eclipse EMF used for java, so if you can grab the idea from there how EMF is working for code generation, probably there are high chances you can get to your goal.

P.S: It was hard for us also to relate them :)
Good Luck,

Zain.

**Comment by mcraveiro** [comment]
Ah, I see. Unfortunately I am doing some research for my thesis, so I need to read up on their paper. My thesis is based on my own code generator [1], which sadly ignored all of the EMF stuff. Now I need to make it compatible with the existing MDE tools, so I am trying to see what I can reuse of EMF4CPP.

Not to worry. Thanks for your time.

[1] https://github.com/DomainDrivenConsulting/dogen

**Comment by dsevilla** [comment]
Hello, @mcraveiro, @qvitech:

First of all, thank you for the interest in the project. Unfortunately, we stopped working on it due to lack of resources some years back. I think Andrés did some later work, but I'm not sure. We are a small lab at a University and we don't have the manpower to continue all our projects, sadly.

I've reviewed the patch and I find it correct but for some weird indent of some files. It would be nice if you could fix that.

I'm merging the request.

As for the paper, I can include it in the github repo itself as a PDF, or I can send you via e-mail (I saw the email). I'll look for it later.

Regards,

**Comment by mcraveiro** [comment]
Hi @dsevilla,

thanks very much for the prompt response. I will try my best to reuse your work and plug it in with mine - it seems very interesting.

In terms of the paper, I think it makes sense to add the PDF to the GitHub repo for future users.

Thanks a lot for your time

Marco

**Pull request merged**
